services:
  api:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["uvicorn", "OnPyRunner.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - ljweel-dev-network


  worker:
    privileged: true
    stop_grace_period: 1s
    cgroup: host
    build:
      context: .
      dockerfile: dockerfile.worker
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["python", "worker.py"]
    deploy:
      resources:
        limits:
          cpus: 1.2
  
  
  redis:
    image: redis:7



networks:
  ljweel-dev-network:
    external: true
    name: ljweel-dev-network